# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4775970c0472390fb6c4a66d7c463b5ecab84201579b115aedb271075436220c91710c7fc5cd24900a1d9e5524e40c0b35480d1bca07fdac664649620f1f272

test:
  secret_key_base: 4b8b2a42a262a6326654a1d53434d884e670197c53036b0c9114684cd0146192a1fe377ea9aba6eaa3be2baa5917368bc0ed4f2f4e5e5ac642a9c8e31d3ddcfd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
